SistemaDeVendas/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SistemaDeVendas.Models;

namespace SistemaDeVendas.Controllers
{
    public class ProdutoController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.ListaProdutos = new ProdutoModel().ListarTodosProdutos();
            return View();
        }

        public IActionResult Cadastro(int? id)
        {
            if (id != null)
            {
                ViewBag.Produto = new ProdutoModel().RetornarProdutoId(id);
            }
            return View();
        }

        [HttpPost]
        public IActionResult Cadastro(ProdutoModel produto)
        {
            if (ModelState.IsValid)
            {
                produto.Gravar();
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Excluir(int id)
        {
            ViewData["IdExcluir"] = id;
            return View();
        }

        public IActionResult ExcluirProduto(int id)
        {
            new ProdutoModel().Excluir(id);
            return View();
        }
    }
}

SistemaDeVendas/Views/Produto/Cadastro.cshtml
@model ProdutoModel

<h2>Cadastro de Produtos</h2>

<form asp-controller="Produto" asp-action="Cadastro">
    <input type="hidden" asp-for="Id" value="@try {@ViewBag.Produto.Id } catch { } " />
    <div class="form-group">
        <label>Nome</label>
        <input asp-for="Nome" type="text" class="form-control" value="@try {@ViewBag.Produto.Nome } catch { }" />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Descrição</label>

        @{
            var vDescricao = "";

            try
            {
                vDescricao = ViewBag.Produto.Descricao;
            }
            catch { }

        }

        @Html.TextArea("Descricao", vDescricao, new { @class = "form-control" })
        <span asp-validation-for="Descricao" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Preço Unitário</label>
        <input asp-for="Preco_Unitario" type="text" class="form-control" value="@try {@ViewBag.Produto.Preco_Unitario } catch { }" />
        <span asp-validation-for="Preco_Unitario" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Quantidade Estoque</label>
        <input asp-for="Quantidade_Estoque" type="text" class="form-control" value="@try {@ViewBag.Produto.Quantidade_Estoque } catch { }" />
        <span asp-validation-for="Quantidade_Estoque" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Unidade Medida</label>
       
        @{
            var vUnidadeMedida = "";
            try
            {
                vUnidadeMedida = ViewBag.Produto.Unidade_Medida;
            }
            catch { }

        }

        <select asp-for="Unidade_Medida" class="form-control">
            @if (vUnidadeMedida != "")
            {
                <option value="@vUnidadeMedida" selected>@vUnidadeMedida</option>
            }

            <option value="un">un</option>
            <option value="cx">cx</option>
            <option value="kg">kg</option>
            <option value="g">g</option>
            <option value="lt">lt</option>
            <option value="ton">ton</option>
        </select>

        <span asp-validation-for="Unidade_Medida" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Link da Foto</label>
        @try
        {
            <img src="@try {@ViewBag.Produto.Unidade_Medida } catch { }" width="150" height="150" />
        }
        catch
        {

        }


        <input asp-for="Link_Foto" type="text" class="form-control" value="@try {@ViewBag.Produto.Link_Foto } catch { }" />
        <span asp-validation-for="Link_Foto" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-block btn-success">Registrar Produto</button>
</form>
<br />
    <button type="button" class="btn btn-block btn-primary" onclick="Voltar()">Listagem de Produtos</button>


    <script>
        function Voltar() {
            window.location.href = '../../Produto/Index';
        }
    </script>

SistemaDeVendas/Views/Produto/Excluir.cshtml
<h2>Excluir Produto?</h2>

<h3>Deseja realmente excluir o produto selecionado?</h3>

<button type="button" class="btn btn-danger" onclick="Nao()">Não</button>
<button type="button" class="btn btn-success" onclick="Sim()">Sim</button>

<script>

    function Sim() {
        window.location.href = '../../Produto/ExcluirProduto/' + ' @ViewData["IdExcluir"].ToString()';

}

function Nao() {
    window.location.href = '../../Produto/Index';
}

</script>

SistemaDeVendas/Views/Produto/ExcluirProduto.cshtml
<h2>Produto excluido com Sucesso!</h2>

<button type="button" class="btn btn-primary" onclick="Voltar()">Listagem de Produtos</button>

<script>
    function Voltar() {
        window.location.href = '../../Produto/Index';
    }

</script>

SistemaDeVendas/Views/Produto/Index.cshtml
<h3>Lista de Produtos</h3>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>#</th>
            <th>Id</th>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço Unitário</th>
            <th>Quantidade no Estoque</th>
            <th>Unidade de Medida</th>
            <th> Foto</th>
        </tr>
    </thead>

    <tbody>
        @{
            foreach (var item in (List<ProdutoModel>)ViewBag.ListaProdutos)
            {
        <tr>
            <td><button type="button" class="btn btn-warning" onclick="Editar(@item.Id)">Editar</button></td>
            <td><button type="button" class="btn btn-danger" onclick="Excluir(@item.Id)">Excluir</button></td>
            <td>@item.Id</td>
            <td>@item.Nome</td>
            <td>@item.Descricao</td>
            <td>@item.Preco_Unitario</td>
            <td>@item.Quantidade_Estoque</td>
            <td>@item.Unidade_Medida</td>
            <td><img src="@item.Link_Foto" width="150" height="150" /></td>
        </tr>
            }
        }
    </tbody>
</table>
<br />
<button class="btn btn-block btn-primary" type="button" onclick="Cadastrar()">Cadastrar Produto</button>

<script>
    function Cadastrar() {    
        window.location.href = "../Produto/Cadastro";
    }

    function Editar(id) {  
        window.location.href = "../Produto/Cadastro/" + id;
    }
    function Excluir(id) {
        window.location.href = "../Produto/Excluir/" + id;
    }
</script>