SistemaDeVendas/Controllers/VendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SistemaDeVendas.Models;

namespace SistemaDeVendas.Controllers
{
    public class VendaController : Controller
    {
        private IHttpContextAccessor httpContext;

        public VendaController(IHttpContextAccessor HttpContextAccessor)
        {
            httpContext = HttpContextAccessor;
        }

        public IActionResult Index()
        {
            ViewBag.ListaVendas = new VendaModel().ListagemVendas();
            return View();
        }

        public IActionResult Registrar()
        {
            CarregarDados();
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(VendaModel venda)
        {
            venda.Vendedor_Id = httpContext.HttpContext.Session.GetString("IdUsuarioLogado");
            venda.Inserir();
            CarregarDados();
            return View();
        }

        private void CarregarDados()
        {
            ViewBag.ListaClientes = new VendaModel().RetornarListaClientes();
            ViewBag.ListaVendedores = new VendaModel().RetornarListaVendedores();
            ViewBag.ListaProdutos = new VendaModel().RetornarListaProdutos();
        }
    }
}

SistemaDeVendas/Views/Venda/Index.cshtml
<h2>Listagem de Vendas</h2>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Data</th>
            <th>Vendedor</th>
            <th>Cliente</th>
            <th>Total</th>
        </tr>
    </thead>

    <tbody>
        @{
            foreach (var item in (List<VendaModel>)ViewBag.ListaVendas)
            {
        <tr>
            <td>@item.Id</td>
            <td>@item.Data</td>
            <td>@item.Vendedor_Id</td>
            <td>@item.Cliente_Id</td>
            <td>R$ @item.Total</td>
        </tr>
            }
        }
    </tbody>
</table>
<br />
<button class="btn btn-block btn-primary" type="button" onclick="Cadastrar()">Registrar Vendas</button>

<script>
    function Cadastrar() {
        window.location.href = "../Venda/Registrar";
    }
</script>

SistemaDeVendas/Views/Venda/Registrar.cshtml
@model VendaModel

<h2>Registrar uma Venda</h2>

<form asp-controller="Venda" asp-action="Registrar">
    @*<input type="hidden" asp-for="Id" value="@try { @ViewBag.Venda.Id } catch { } " />*@

    <div class="form-group">
        <label>Cliente</label>
        <select asp-for="Cliente_Id" class="form-control">
            @{
                foreach (var item in (List<ClienteModel>)ViewBag.ListaClientes)
                {
                    <option value="@item.Id">@item.Nome</option>
                }
            }
        </select>
    </div>

    <label>Produtos</label>
    <br /><br />
    <div class="form-group">
        <div class="col-lg-9">
            <select class="form-control" id="sltProduto">
                @{
                    foreach (var item in (List<ProdutoModel>)ViewBag.ListaProdutos)
                    {
                        <option value="@item.Id">@item.Nome | @item.Preco_Unitario</option>
                    }
                }
            </select>
        </div>
        <div class="col-lg-1">
            <input type="text" class="form-control" value="1" id="txtQuantidade" />
        </div>
        <div class="col-lg-2">
            <button type="button" class="btn btn-block btn-primary" onclick="AdicionarProduto()">Adicionar</button>
        </div>
    </div>

    <br /><br />
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Id</td>
                <td>Nome</td>
                <td>Quantidade</td>
                <td>Preço Unitário</td>
                <td>Total</td>
            </tr>
        </thead>

        <tbody id="listaProdutos"></tbody>
    </table>

    <div style="float:left; font-size:22px;">Total: R$ </div>
    <div style="float:left; font-size: 22px; margin-left:5px;" id="divTotal">0.00</div>

    <input type="hidden" id="txtTotal" asp-for="Total" />

    <br /><br />

    <textarea asp-for="ListaProdutos" id="ListaProdutosJSON" style="display:inline;"></textarea>

    <button type="submit" class="btn btn-block btn-success">Registrar</button>
    <button type="button" class="btn btn-block btn-primary" onclick="Voltar()">Listagem de Vendas</button>
</form>

<script>
    var Itens = new Object();
    Itens.Produtos = new Array();

    var CodigoProduto = document.getElementById("sltProduto");
    var QtdProduto = document.getElementById("txtQuantidade");
    var ListaProdutos = document.getElementById("listaProdutos");
    var TotalVenda = document.getElementById("divTotal");
    var txtTotal = document.getElementById("txtTotal");
    var ListaProdutosJSON = document.getElementById("ListaProdutosJSON");

    function Voltar() {
        window.location.href = '../Venda/Index';
    }

    function AdicionarProduto() {

        var DescricaoPreco = CodigoProduto.options[CodigoProduto.selectedIndex].text;
        var arrayDescricaoPreco = DescricaoPreco.split('|');

        var total = (arrayDescricaoPreco[1].replace(",", ".") * QtdProduto.value);
        total = Math.round(total * 100) / 100;

        Itens.Produtos.push({
            "CodigoProduto": CodigoProduto.value,
            "DescricaoProduto": arrayDescricaoPreco[0],
            "QtdProduto": QtdProduto.value,
            "PrecoUnitario": arrayDescricaoPreco[1],
            "Total": total
        });

        ListaProdutosJSON.innerHTML = JSON.stringify(Itens.Produtos);

        var produto = "<tr>" +
            "<td>" + CodigoProduto.value + "</td>" + 
            "<td>" + arrayDescricaoPreco[0] + "</td>" +
            "<td>" + QtdProduto.value + "</td>" + 
            "<td> R$ " + arrayDescricaoPreco[1] + "</td>" +
            "<td> R$ " + total + "</td>" + 
            "<tr>";

        ListaProdutos.innerHTML += produto;
        var totalGeral = Math.round((TotalVenda.innerText * 1 + total) * 100) / 100;
        TotalVenda.innerHTML = totalGeral;
        txtTotal.value = totalGeral;
    }

</script>