SistemaDeVendas/Controllers/RelatorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SistemaDeVendas.Models;

namespace SistemaDeVendas.Controllers
{
    public class RelatorioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Vendas()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Vendas(RelatorioModel relatorio)
        {
            if (relatorio.DataDe.Year == 1)
            {
                ViewBag.ListaVendas = new VendaModel().ListagemVendas();
            }
            else
            {
                string DataDe = relatorio.DataDe.ToString("yyyy/MM/dd");
                string DataAte = relatorio.DataAte.ToString("yyyy/MM/dd");
                ViewBag.ListaVendas = new VendaModel().ListagemVendas(DataDe, DataAte);
            }

            return View();
        }

        public IActionResult Grafico()
        {
            List<GraficoProdutos> lista = new GraficoProdutos().RetornarGrafico();
            string valores = "";
            string labels = "";
            string cores = "";

            var random = new Random();

            //Itens do Gráfico
            for (int i = 0; i < lista.Count; i++)
            {
                valores += lista[i].QtdVendido.ToString() + ",";
                labels += "'" + lista[i].DescricaoProduto.ToString() + "',";
                cores += "'" + String.Format("#{0:X6}", random.Next(0x1000000)) + "',";
            }

            ViewBag.Valores = valores;
            ViewBag.Labels = labels;
            ViewBag.Cores = cores;

            return View();
        }

        public IActionResult Comissao()
        {
            return View();
        }
    }
}

SistemaDeVendas/Controllers/VendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SistemaDeVendas.Models;

namespace SistemaDeVendas.Controllers
{
    public class VendaController : Controller
    {
        private IHttpContextAccessor httpContext;

        public VendaController(IHttpContextAccessor HttpContextAccessor)
        {
            httpContext = HttpContextAccessor;
        }

        public IActionResult Index()
        {
            ViewBag.ListaVendas = new VendaModel().ListagemVendas();
            return View();
        }

        public IActionResult Registrar()
        {
            CarregarDados();
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(VendaModel venda)
        {
            venda.Vendedor_Id = httpContext.HttpContext.Session.GetString("IdUsuarioLogado");
            venda.Inserir();
            CarregarDados();
            return View();
        }

        private void CarregarDados()
        {
            ViewBag.ListaClientes = new VendaModel().RetornarListaClientes();
            ViewBag.ListaVendedores = new VendaModel().RetornarListaVendedores();
            ViewBag.ListaProdutos = new VendaModel().RetornarListaProdutos();
        }
    }
}

SistemaDeVendas/Views/Relatorio/Comissao.cshtml
<h2>Comissao</h2>

SistemaDeVendas/Views/Relatorio/Grafico.cshtml
<h2>Grafico de vendas por produtos</h2>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>

<div id="canvas-holder" style="width:40%">
    <canvas id="chart-area"></canvas>
</div>

<script>
    var randomScalingFactor = function () {
        return Math.round(Math.random() * 100);
    };

    var config = {
        type: 'pie',
        data: {
            datasets: [{
                data: [@Html.Raw(ViewBag.Valores)],                     
                backgroundColor: [@Html.Raw(ViewBag.Cores)], 
                label: 'Dataset 1'
            }],
            labels: [@Html.Raw(ViewBag.Labels)]   
        },
        options: {
            responsive: true
        }
    };

    window.onload = function () {
        var ctx = document.getElementById('chart-area').getContext('2d');
        window.myPie = new Chart(ctx, config);
    };

</script>

SistemaDeVendas/Views/Relatorio/Index.cshtml
<h2>Relatório do Sistema</h2>

<button class="btn btn-block btn-primary" type="button" onclick="Relatorio('Vendas')">Vendas por Período</button>
<button class="btn btn-block btn-warning" type="button" onclick="Relatorio('Grafico')">Gráfico de Vendas</button>
<button class="btn btn-block btn-success" type="button" onclick="Relatorio('Comissao')">Comissão de Vendedores</button>


<script>

    function Relatorio(action) {
        window.location.href = "../Relatorio/" + action;
    }

</script>

SistemaDeVendas/Views/Relatorio/Vendas.cshtml
@model RelatorioModel

<h2>Vendas por Período</h2>

<form asp-controller="Relatorio" asp-action="Vendas">
    <div class="form-group">
        <label>Período</label>
        <input asp-for="DataDe" type="date" class="form-control" />
    </div>
    <div class="form-group">
        <input asp-for="DataAte" type="date" class="form-control" />
    </div>

    <button type="submit" class="btn btn-block btn-success">Pesquisar</button>
</form>
<br />
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Data</th>
            <th>Vendedor</th>
            <th>Cliente</th>
            <th>Total</th>
        </tr>
    </thead>

    <tbody>
        @{
            try
            {
                foreach (var item in (List<VendaModel>)ViewBag.ListaVendas)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Data</td>
                        <td>@item.Vendedor_Id</td>
                        <td>@item.Cliente_Id</td>
                        <td>R$ @item.Total</td>
                    </tr>
                }
            }
            catch { }

        }
    </tbody>
</table>